name: GitHub Actions Demo
on:
    push:
        branches:
            - 'main'
        paths-ignore:
            - '.github/**'
    pull_request:
        branches:
            - 'main'
    schedule:
        - cron: "15 6 * * 7"
    workflow_dispatch:

jobs:
    Build:
        runs-on: ubuntu-latest
        steps:
            - name: Workflow name
              shell: bash
              run: |
                echo ${{ github.event_name }}

            - name: Branch name
              shell: bash
              run: |
                echo ${{ github.base_ref }}

            - name: Files
              shell: bash
              run: |
                  ls -al
  
